module.exports = [
	'Arts',
	'Arts :: Design',
	'Arts :: Fashion & Beauty',
	'Arts :: Food',
	'Arts :: Books',
	'Arts :: Performing Arts',
	'Arts :: Visual Arts',
	'Business',
	'Business :: Careers',
	'Business :: Entrepreneurship',
	'Business :: Investing',
	'Business :: Management',
	'Business :: Marketing',
	'Business :: Non-profit',
	'Comedy',
	'Comedy :: Comedy Interviews',
	'Comedy :: Improv',
	'Comedy :: Stand-Up',
];
